// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fypfbsneyoakfwhnquks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5cGZic25leW9ha2Z3aG5xdWtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MzUxOTcsImV4cCI6MjA2NjQxMTE5N30.3C2393TL8VPcy6RLu8Fx0HSGWDgc67Vy29J0iAO0vyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);